on:
  pull_request:
  push:

  schedule:
    - cron: "0 12 */3 * *"

name: Check

jobs:
  pre-commit:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Build project
        run: make
      - name: Print arduino-cli output
        run: cat bounce-builder-logs.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Bounce
          path: |
            build/
            bounce-builder-logs.txt
          if-no-files-found: error
